gText_Birch_Welcome::
	.string "Hello! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is OAK.\p"
	.string "People affectionately refer to me\n"
	.string "as the POKéMON PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "People and POKéMON live together by\n"
	.string "supporting each other.\p"
	.string "Some people play with POKéMON,\n"
	.string "some battle with them.\p"
	.string "But despite this, we don't know\n"
	.string "everything about POKéMON yet.\p"
	.string "There are still many mysteries\n"
	.string "surrounding them to solve.\p"
	.string "That's why I study POKéMON as a\n"
	.string "profession every day.\p"
	.string "Now, enough about me.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Tell me a little about yourself.\p$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "Now, what did you say your name\n"
	.string "was again?$"

gText_Birch_SoItsPlayer::
	.string "Right…\n"
	.string "So your name is {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "{PLAYER}{KUN}, are you ready?\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Your very own POKéMON story is\n"
	.string "about to unfold.\p"
	.string "You'll face fun times and tough\n"
	.string "challenges.\p"
	.string "A world of dreams and adventures\n"
	.string "with POKéMON awaits! Let's go!\p"
	.string "I'll be seeing you later!$"
	.string "$"
